keycloak.url=http://localhost:8080
keycloak.realm=monitoring
keycloak.client-id=auth-service
keycloak.client-secret=fYMNVHQs90uEaJu8eB1SgrVp5Zz2FR9v

spring.kafka.bootstrap-servers=localhost:9092

producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/monitoring

server.port=8084